name: Deploy Dart Frog API

on:
  workflow_call:
    inputs:
      code_path:
        description: "Path where the Dart Frog API is located."
        required: false
        type: string
      dart_sdk:
        description: "The Dart version used to build this API"
        required: true
        type: string
        default: "stable"
      namespace:
        description: "The user or org to publish this image"
        required: true
        type: string
      image:
        description: "The name of this image"
        required: true
        type: string
      tag:
        description: "The tag for this image"
        required: true
        type: string
        default: ${{ github.sha }}
      

jobs:
  build-and-deploy:
    name: Build and Deploy Api
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.dart_sdk }}

      - name: Install Dart Frog
        run: dart pub global activate dart_frog_cli

      - name: Dart Frog Build
        run: dart_frog build
        working-directory: ${{ inputs.code_path }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        run: |-
          docker build -t ghcr.io/${{ inputs.namespace }}/${{ inputs.image }}:${{  inputs.tag }} build
          docker push ghcr.io/${{ inputs.namespace }}/${{ inputs.image }}:${{ inputs.tag }}
        working-directory: ${{ inputs.code_path }}
